name: crosssight-rtdetr
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.2.2
  - torchvision=0.17.2
  - pytorch-cuda=12.1
  - pip:
      - -r requirements.txt
